# Generated by Django 6.0 on 2025-12-12 20:54

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('movies', '0001_initial'), ('movies', '0002_movie_evaluation'), ('movies', '0003_add_favorite_movies'), ('movies', '0004_author_source_movie_source'), ('movies', '0005_author_tmdb_id_movie_tmdb_id'), ('movies', '0006_alter_author_source_alter_movie_release_date_and_more'), ('movies', '0007_remove_author_website')]

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('biography', models.TextField(blank=True, default='')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, default='', max_length=100)),
                ('source', models.CharField(choices=[('admin', 'Admin'), ('tmdb', 'TMDB')], db_index=True, default='admin', max_length=10)),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
            bases=('users.baseuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Spectator',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, default='')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Spectator',
                'verbose_name_plural': 'Spectators',
            },
            bases=('users.baseuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True, default='')),
                ('tagline', models.CharField(blank=True, default='', max_length=500)),
                ('release_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('rumored', 'Rumored'), ('planned', 'Planned'), ('in_production', 'In Production'), ('post_production', 'Post Production'), ('released', 'Released'), ('canceled', 'Canceled')], db_index=True, default='released', max_length=20)),
                ('budget', models.PositiveBigIntegerField(blank=True, null=True)),
                ('revenue', models.PositiveBigIntegerField(blank=True, null=True)),
                ('original_language', models.CharField(blank=True, default='en', max_length=10)),
                ('adult', models.BooleanField(default=False)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='movies', to='movies.author')),
                ('evaluation', models.CharField(blank=True, choices=[('masterpiece', 'Masterpiece'), ('good', 'Good'), ('average', 'Average'), ('terrible', 'Terrible')], default='', max_length=20)),
                ('source', models.CharField(choices=[('admin', 'Admin'), ('tmdb', 'TMDB')], db_index=True, default='admin', max_length=10)),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='MovieRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(help_text='Rating from 1 to 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('review', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movies.movie')),
                ('spectator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_ratings', to='movies.spectator')),
            ],
            options={
                'verbose_name': 'Movie Rating',
                'verbose_name_plural': 'Movie Ratings',
                'ordering': ['-created_at'],
                'unique_together': {('spectator', 'movie')},
            },
        ),
        migrations.CreateModel(
            name='AuthorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(help_text='Rating from 1 to 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('review', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movies.author')),
                ('spectator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_ratings', to='movies.spectator')),
            ],
            options={
                'verbose_name': 'Author Rating',
                'verbose_name_plural': 'Author Ratings',
                'ordering': ['-created_at'],
                'unique_together': {('spectator', 'author')},
            },
        ),
        migrations.AddField(
            model_name='spectator',
            name='favorite_movies',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='movies.movie'),
        ),
    ]
