# Generated by Django 6.0 on 2025-12-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_movie_evaluation"),
    ]

    operations = [
        migrations.AddField(
            model_name="spectator",
            name="favorite_movies",
            field=models.ManyToManyField(
                blank=True, related_name="favorited_by", to="movies.movie"
            ),
        ),
    ]
