# Generated by Django 6.0 on 2025-12-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_add_favorite_movies"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="source",
            field=models.CharField(
                choices=[("admin", "Admin"), ("tmdb", "TMDB")],
                default="admin",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="source",
            field=models.CharField(
                choices=[("admin", "Admin"), ("tmdb", "TMDB")],
                default="admin",
                max_length=10,
            ),
        ),
    ]
