# Generated by Django 6.0 on 2025-12-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_author_source_movie_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="tmdb_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="tmdb_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
