# Generated by Django 6.0 on 2025-12-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0005_author_tmdb_id_movie_tmdb_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="source",
            field=models.CharField(
                choices=[("admin", "Admin"), ("tmdb", "TMDB")],
                db_index=True,
                default="admin",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="source",
            field=models.CharField(
                choices=[("admin", "Admin"), ("tmdb", "TMDB")],
                db_index=True,
                default="admin",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="status",
            field=models.CharField(
                choices=[
                    ("rumored", "Rumored"),
                    ("planned", "Planned"),
                    ("in_production", "In Production"),
                    ("post_production", "Post Production"),
                    ("released", "Released"),
                    ("canceled", "Canceled"),
                ],
                db_index=True,
                default="released",
                max_length=20,
            ),
        ),
    ]
