# Generated by Django 6.0 on 2025-12-12 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_author_source_alter_movie_release_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='website',
        ),
    ]
